const std = @import("std");

// Strings installed by the standard libraries are part of the executable and
// live for the duration of the process. Keeping one canonical static slice for
// each value avoids allocating and GC-tracking the same names in every state.
pub const names = [_][]const u8{
    "",
    "/",
    "\\",
    "r",
    "w",
    "_G",
    "fs",
    "io",
    "os",
    "pi",
    "abs",
    "cos",
    "csv",
    "deg",
    "exp",
    "len",
    "log",
    "max",
    "min",
    "rad",
    "rep",
    "sin",
    "sub",
    "tan",
    "ult",
    "__gc",
    "acos",
    "asin",
    "atan",
    "byte",
    "ceil",
    "char",
    "copy",
    "date",
    "dump",
    "find",
    "fmod",
    "full",
    "gsub",
    "huge",
    "join",
    "json",
    "list",
    "load",
    "math",
    "modf",
    "move",
    "next",
    "null",
    "open",
    "pack",
    "path",
    "read",
    "seek",
    "sort",
    "sqrt",
    "stat",
    "stem",
    "time",
    "toml",
    "type",
    "utf8",
    "walk",
    "warn",
    "wrap",
    "FILE*",
    "clock",
    "close",
    "codes",
    "cpath",
    "debug",
    "dedup",
    "error",
    "floor",
    "flush",
    "frexp",
    "input",
    "ldexp",
    "lines",
    "lower",
    "match",
    "mkdir",
    "pairs",
    "pcall",
    "print",
    "split",
    "stdin",
    "strip",
    "table",
    "touch",
    "upper",
    "write",
    "yield",
    "__name",
    "assert",
    "concat",
    "config",
    "create",
    "dofile",
    "exists",
    "format",
    "getenv",
    "gmatch",
    "insert",
    "ipairs",
    "loaded",
    "offset",
    "output",
    "random",
    "rawget",
    "rawlen",
    "rawset",
    "remove",
    "rename",
    "resume",
    "rsplit",
    "select",
    "status",
    "stderr",
    "stdout",
    "string",
    "unpack",
    "xpcall",
    "Lua 5.5",
    "__close",
    "__index",
    "__metatable",
    "dirname",
    "execute",
    "gethook",
    "getinfo",
    "msgpack",
    "package",
    "preload",
    "require",
    "reverse",
    "running",
    "scandir",
    "sethook",
    "setvbuf",
    "tmpfile",
    "tmpname",
    "_VERSION",
    "basename",
    "difftime",
    "getlocal",
    "loadfile",
    "open_dir",
    "packsize",
    "rawequal",
    "relative",
    "setlocal",
    "tonumber",
    "tostring",
    "codepoint",
    "coroutine",
    "extension",
    "normalize",
    "searchers",
    "separator",
    "setlocale",
    "tointeger",
    "traceback",
    "upvalueid",
    "/\n;\n?\n!\n-\n",
    "getupvalue",
    "maxinteger",
    "mininteger",
    "randomseed",
    "searchpath",
    "setupvalue",
    "zerde null",
    "__zlua_file",
    "charpattern",
    "getregistry",
    "is_absolute",
    "isyieldable",
    "upvaluejoin",
    "zerde array",
    "__zlua_input",
    "getmetatable",
    "getuservalue",
    "setmetatable",
    "setuservalue",
    "zerde object",
    "__zlua_output",
    "[\x00-\x7F\xC2-\xFD][\x80-\xBF]*",
    "collectgarbage",
    "__zlua_file_pos",
    "__zlua_file_mode",
    "__zlua_file_path",
    "__zlua_file_closed",
    "__zlua_file_content",
    "./?.lua;./?/init.lua",
    "__zlua_file_standard",
    "__zlua_file_buffer_mode",
};

const StaticMap = std.StaticStringMap(usize);
const canonical_map: StaticMap = blk: {
    var entries: [names.len]struct { []const u8, usize } = undefined;
    for (names, 0..) |name, index| entries[index] = .{ name, index };
    break :blk StaticMap.initComptime(entries);
};

pub fn canonical(bytes: []const u8) ?[]const u8 {
    const index = canonical_map.get(bytes) orelse return null;
    return names[index];
}

pub fn get(comptime bytes: []const u8) []const u8 {
    return comptime canonical(bytes) orelse @compileError("missing standard-library static string: " ++ bytes);
}

test "all static strings are canonical" {
    for (names) |name| {
        const value = canonical(name) orelse return error.TestUnexpectedResult;
        try std.testing.expectEqual(name.ptr, value.ptr);
    }
}
